### ISSUE TITLE
Quoted text unsupported

### ISSUE THREAD

**Issue by mpskovvang** [oovm/fluent-intellij#4]
Apparently, quoted text is not currently supported:

![image](https://user-images.githubusercontent.com/7034075/150142505-12330836-bb21-45ad-be91-f466cc172c60.png)

According to the [Fluent specification](https://projectfluent.org/fluent/guide/special.html#escape-sequences), unescaped double quotes is the preferred way, but neither does it work with escaping `{"\""}`.

Thanks for your effort in this plugin. Makes maintaining a language template a lot easier.

**Comment by oovm** [comment]
Thanks for your feedback, this looks the same as #1 A new version is under review

**Comment by oovm** [comment]
This version under review does not solve the formatting problem, so don't use the formatting function for the time being. I have encountered some technical difficulties and I am sorry that I cannot solve it in a short time.

**Comment by mpskovvang** [comment]
Sorry, you're right - forgot to check closed issues.

I haven't used formatting functionality yet, but that probably explains the wrong indents after pasting messages.

**Comment by oovm** [comment]
Should fixed by today’s update

**Comment by mpskovvang** [comment]
Indeed it is. Thanks!

But apparently, the first attribute per message is no longer highlighted with yellow - only the following.

![image](https://user-images.githubusercontent.com/7034075/150699708-dcdb47ae-5514-415c-8b93-b8ba8b45a75d.png)

**Comment by oovm** [comment]
I have released another version
