### ISSUE TITLE
Support for attributes in placeables

### ISSUE THREAD

**Issue by Karabur** [oovm/fluent-intellij#8]
In a fluent is allowed to write 
```
message = hello
     .attribute = I am attribute

say-something = some text { message.attribute }
```

Plugin does not understand that syntax and produces error 
`FluentTokenType.(, FluentTokenType.->, FluentTokenType.. or FluentTokenType.} expected, got '.'`

**Comment by oovm** [comment]
![image](https://user-images.githubusercontent.com/17541209/177724296-9756b180-c499-4e0c-946e-7c03aeced722.png)

A new version is under review
