### ISSUE TITLE
IntelliJ 2022.3 support

### ISSUE THREAD

**Issue by morespacemore** [oovm/fluent-intellij#9]
![image](https://user-images.githubusercontent.com/56313857/205477614-2090ca6c-0b73-48b8-b405-6502c8d9c668.png)

**Comment by oovm** [comment]
The new version has entered review.

![%O9}`Y8Z~L_W$ETH}3}Z}DX](https://user-images.githubusercontent.com/17541209/205542713-b5acc387-8fe1-4cd3-9d68-e4bbbe1903cb.png)

**Comment by oovm** [comment]
Version approved, please let me know if you have any questions.

**Comment by morespacemore** [comment]
Thanks, everything works
